import{a as y,S as q,i as E}from"./assets/vendor-5401a4b0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const g=15;y.defaults.baseURL="https://pixabay.com/api/";const M="42577759-46afea0faf18c5517840853c6";async function h(o,e){const{data:i}=await y.get("",{params:{page:o,per_page:g,key:M,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0}});return i}function L(o,e){const i=o.map(({webformatURL:l,largeImageURL:t,tags:r,likes:a,views:b,comments:S,downloads:w})=>`<li class="gallery-item">
                    <a href="${t}">
                        <img class="gallery-image"
                            src="${l}" 
                            alt="${r}" />
                    </a>
                    <ul class="image-info">
                        <li class="image-info-item">Likes<p class="info">${a}</p></li>
                        <li class="image-info-item">Views<p class="info">${b}</p></li>
                        <li class="image-info-item">Comments<p class="info">${S}</p></li>
                        <li class="image-info-item">Downloads<p class="info">${w}</p></li>
                    </ul>
                </li>`).join("");e.insertAdjacentHTML("beforeend",i)}const f=document.querySelector(".gallery-list"),m=document.querySelector(".form"),P=document.querySelector(".input-value-js"),c=document.querySelector(".form-container div"),p=document.querySelector(".loading"),s=document.querySelector(".load-more-markup"),v=new q(".gallery-list a",{captionsData:"alt",captionDelay:250});let u,d;s.classList.add("hidden");m.addEventListener("submit",$);async function $(o){if(o.preventDefault(),u=1,d=P.value.trim(),f.innerHTML=null,s.classList.add("hidden"),d===""){n("Sorry, input is emty!","#FFA000");return}c.classList.add("loader");try{const e=await h(u,d);if(e.total===0){c.classList.add("loader"),n("Sorry, there are no images matching your search query. Please try again!","#EF4040"),c.classList.remove("loader"),m.reset();return}L(e.hits,f),v.refresh(),window.scrollBy({top:85,behavior:"smooth"}),c.classList.remove("loader"),s.classList.remove("hidden")}catch{n("Error","#EF4040")}m.reset()}s.addEventListener("click",F);async function F(o){u++,p.classList.add("loader"),s.classList.add("hidden");try{const e=await h(u,d);if(L(e.hits,f),window.scrollBy({top:500,behavior:"smooth"}),e.totalHits<g)return s.classList.add("hidden"),n("We're sorry, but you've reached the end of search results.");v.refresh(),p.classList.remove("loader"),s.classList.remove("hidden")}catch{n("Error")}}function n(o,e){E.info({position:"topRight",message:o,messageColor:"#ffffff",backgroundColor:e,messageSize:16,layout:2,maxWidth:380})}
//# sourceMappingURL=commonHelpers.js.map
