import{a as m,S as v,i as E}from"./assets/vendor-5401a4b0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const p=15;m.defaults.baseURL="https://pixabay.com/api/";const q="42577759-46afea0faf18c5517840853c6";async function g(o,e){const{data:i}=await m.get("",{params:{page:o,per_page:p,key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0}});return i}function y(o,e){const i=o.map(({webformatURL:n,largeImageURL:t,tags:r,likes:s,views:L,comments:S,downloads:b})=>`<li class="gallery-item">
                    <a href="${t}">
                        <img class="gallery-image"
                            src="${n}" 
                            alt="${r}" />
                    </a>
                    <ul class="image-info">
                        <li class="image-info-item">Likes<p class="info">${s}</p></li>
                        <li class="image-info-item">Views<p class="info">${L}</p></li>
                        <li class="image-info-item">Comments<p class="info">${S}</p></li>
                        <li class="image-info-item">Downloads<p class="info">${b}</p></li>
                    </ul>
                </li>`).join("");e.insertAdjacentElement("beforeend",i)}const u=document.querySelector(".gallery-list"),f=document.querySelector("form"),w=document.querySelector("input"),P=document.querySelector(".form-container div");document.querySelector(".loading");const d=document.querySelector(".load-more-markup"),h=new v(".gallery-list a",{captionsData:"alt",captionDelay:250});let l,c;d.classList.add("hidden");f.addEventListener("submit",$);async function $(o){if(o.preventDefault(),l=1,c=w.value.trim(),u.innerHTML="",c===""){a("Sorry, input is emty!","#FFA000");return}P.classList.add("loader");try{const e=await g(l,c);if(e.total===0){a("Sorry, there are no images matching your search query. Please try again!","#EF4040"),f.reset();return}console.log(e.hits),y(e.hits,u),h.refresh(),console.log(e.hits)}catch{a("Error","#EF4040")}f.reset()}d.addEventListener("click",F);async function F(o){l++;try{const e=g(l,c);if(y(e.hits,u),window.scrollBy({top:575.6666870117188,behavior:"smooth"}),e.hits.length<p)return d.classList.add("hidden"),a("We're sorry, but you've reached the end of search results.");h.refresh()}catch{a("Error")}}function a(o,e){E.info({position:"topRight",message:o,messageColor:"#ffffff",backgroundColor:e,messageSize:16,layout:2,maxWidth:380})}
//# sourceMappingURL=commonHelpers.js.map
